# Generated by Django 3.1.7 on 2021-07-21 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='organizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificación', models.CharField(max_length=15, verbose_name='Identificación Organizacion')),
                ('nombre_organizacion', models.CharField(max_length=70, verbose_name='Identificación Organizacion')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(default=None)),
                ('fecha_registro', models.DateField(default=None)),
                ('correo', models.ImageField(default='null@null.com', null=True, upload_to='', verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, null=True, verbose_name='Telefono')),
                ('direccion1', models.TextField(verbose_name='Direccion 1')),
                ('direccion2', models.TextField(null=True, verbose_name='Direccion 2')),
                ('logo', models.ImageField(upload_to='organizaciones/logos')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=4, verbose_name='cod')),
                ('descripcion', models.CharField(max_length=30, verbose_name='cod')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacionn.organizaciones', verbose_name='Organizacion')),
                ('id_usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='redes_sociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('mask', models.CharField(max_length=15, verbose_name='Maskara web')),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacionn.organizaciones', verbose_name='Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='autoridades_organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=15, verbose_name='Identificación')),
                ('nombre_apellido', models.CharField(max_length=70, verbose_name='Nombres y Apellidos')),
                ('telefono', models.CharField(max_length=10, null=True, verbose_name='Telefono')),
                ('correo', models.EmailField(default='null@null.com', max_length=254, null=True, verbose_name='Correo')),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacionn.organizaciones', verbose_name='Organizacion')),
                ('id_tipo_autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacionn.tipo_autoridad', verbose_name='Organizacion')),
            ],
        ),
    ]
