# Generated by Django 3.1.7 on 2021-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacionn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizaciones',
            name='correo',
            field=models.EmailField(default='null@null.com', max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='organizaciones',
            name='nombre_organizacion',
            field=models.CharField(max_length=70, verbose_name='Nombre Organizacion'),
        ),
    ]
