# Generated by Django 3.1.7 on 2021-12-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacionn', '0002_auto_20210721_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridades_organizacion',
            name='id_tipo_autoridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacionn.tipo_autoridad', verbose_name='Tipo autoridad'),
        ),
    ]
