# Generated by Django 3.1.7 on 2021-04-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=50, verbose_name='Nombre Institucion')),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('correo', models.EmailField(default=None, max_length=254)),
                ('ruc', models.CharField(max_length=15, verbose_name='Ruc')),
                ('logo', models.ImageField(upload_to='')),
                ('logo_url', models.CharField(max_length=50, verbose_name='Url')),
            ],
        ),
    ]
