# Generated by Django 3.1.7 on 2021-07-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_noticias_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias_index',
            name='imagen',
            field=models.ImageField(upload_to='noticias'),
        ),
    ]
