# Generated by Django 3.1.7 on 2021-12-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacionn', '0003_auto_20211218_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, verbose_name='Nombre Categoria')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='unidad_medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(max_length=10, verbose_name='Nombre Medida')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('desc_beneficio', models.TextField()),
                ('fecha_registro', models.DateField(default=None)),
                ('id_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacionn.organizaciones', verbose_name='id_organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presentacion', models.CharField(max_length=100, verbose_name='Nombre Presentacion')),
                ('detalles', models.TextField(null=True)),
                ('estado', models.BooleanField(default=False)),
                ('cont_neto', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria', verbose_name='id_categoria')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='id_producto')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.unidad_medida', verbose_name='id_unidad Medida')),
            ],
        ),
    ]
