# Generated by Django 3.1.7 on 2022-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion',
            name='logo',
            field=models.ImageField(default=1, upload_to='organizaciones/productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion',
            name='precio_mayor',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
