# Generated by Django 3.1.7 on 2022-01-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20220101_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fecha_registro',
            field=models.DateField(default=None),
        ),
    ]
